collections:
  authors:
    output: true
  categories:
    output: true


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "categories"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yo soy root
email: wendyfabianpanganiban@gmail.com
author: Wendy Panganiban